#!/bin/bash
sudo apt purge --ignore-missing \
fwupd \
fwupd-signed \
#libfwupd2 \
#libfwupdplugin5 \
breeze-cursor-theme \
breeze-icon-theme \
catfish \
fonts-beng \
fonts-beng-extra \
fonts-deva \
fonts-deva-extra \
fonts-gargi \
fonts-gubbi \
fonts-gujr \
fonts-gujr-extra \
fonts-guru \
fonts-guru-extra \
fonts-kacst \
fonts-kacst-one \
fonts-kalapi \
fonts-khmeros-core \
fonts-lao \
fonts-lklug-sinhala \
fonts-lohit-beng-assamese \
fonts-lohit-beng-bengali \
fonts-lohit-deva \
fonts-lohit-gujr \
fonts-lohit-guru \
fonts-lohit-knda \
fonts-lohit-mlym \
fonts-lohit-orya \
fonts-lohit-taml \
fonts-lohit-taml-classical \
fonts-lohit-telu \
#fonts-mathjax \
#fonts-mlym \
fonts-nakula \
fonts-navilu \
fonts-noto-cjk \
fonts-orya-extra \
fonts-pagul \
fonts-sahadeva \
fonts-samyak-deva \
fonts-samyak-gujr \
fonts-samyak-mlym \
fonts-samyak-taml \
fonts-sarai \
fonts-sil-abyssinica \
fonts-sil-padauk \
fonts-smc \
fonts-smc-anjalioldlipi \
fonts-smc-chilanka \
fonts-smc-dyuthi \
fonts-smc-gayathri \
fonts-smc-karumbi \
fonts-smc-keraleeyam \
fonts-smc-manjari \
fonts-smc-meera \
fonts-smc-rachana \
fonts-smc-raghumalayalamsans \
fonts-smc-suruma \
fonts-smc-uroob \
fonts-telu-extra \
fonts-teluguvijayam \
fonts-thai-tlwg \
fonts-tibetan-machine \
fonts-tlwg-garuda \
fonts-tlwg-garuda-ttf \
fonts-tlwg-kinnari \
fonts-tlwg-kinnari-ttf \
fonts-tlwg-laksaman \
fonts-tlwg-laksaman-ttf \
fonts-tlwg-loma \
fonts-tlwg-loma-ttf \
fonts-tlwg-mono \
fonts-tlwg-mono-ttf \
fonts-tlwg-norasi \
fonts-tlwg-norasi-ttf \
fonts-tlwg-purisa \
fonts-tlwg-purisa-ttf \
fonts-tlwg-sawasdee \
fonts-tlwg-sawasdee-ttf \
fonts-tlwg-typewriter \
fonts-tlwg-typewriter-ttf \
fonts-tlwg-typist \
fonts-tlwg-typist-ttf \
fonts-tlwg-typo \
fonts-tlwg-typo-ttf \
fonts-tlwg-umpush \
fonts-tlwg-umpush-ttf \
fonts-tlwg-waree \
fonts-tlwg-waree-ttf \
fonts-yrsa-rasa \
fonts-indic \
fonts-knda \
fonts-orya \
fonts-taml \
fonts-telu \
#libjs-mathjax \
thingy \
drawing \
eject \
evolution-data-server \
evolution-data-server-common \
geoip-database \
hexchat \
hexchat-common \
hunspell-de-at-frami \
hunspell-de-ch-frami \
hunspell-de-de-frami \
hunspell-en-au \
hunspell-en-ca \
hunspell-en-gb \
hunspell-en-us \
hunspell-en-za \
hunspell-es \
hunspell-fr \
hunspell-fr-classical \
hunspell-it \
hunspell-pt-br \
hunspell-pt-pt \
hunspell-ru \
hyphen-de \
hyphen-en-ca \
hyphen-en-gb \
hyphen-en-us \
hyphen-fr \
hyphen-it \
hyphen-pt-br \
hyphen-pt-pt \
hyphen-ru \
hypnotix \
librhythmbox-core10 \
casper \
gir1.2-rb-3.0 \
libebackend-1.2-10 \
libebook-1.2-20 \
libebook-contacts-1.2-3 \
libecal-2.0-1 \
libedata-book-1.2-26 \
libedata-cal-2.0-1 \
libedataserver-1.2-26 \
libedataserverui-1.2-3 \
rhythmbox-plugin-tray-icon \
rhythmbox-plugins \
transmission-gtk \
simple-scan \
thunderbird \
webapp-manager \
pix \
pix-data \
pix-dbg \
rhythmbox \
rhythmbox-data \
sticky \
transmission-common \
simple-scan \
webapp-manager \
liblouis-data \
warpinator \
wbrazilian \
wbritish \
wfrench \
witalian \
wngerman \
wportuguese \
wspanish \
wswiss \
youtube-dl \
brltty \
liblouis20 \
liblouisutdml-bin \
liblouisutdml9 \
orca \
python3-louis \
hyphen-fi \
hyphen-ga \
hyphen-id \
mythes* \
speech-dispatcher \
nano
